# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.actionFileopen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/folder-open-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileopen.setIcon(icon)
        self.actionFileopen.setObjectName("actionFileopen")
        self.actionFilesave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/save-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilesave.setIcon(icon1)
        self.actionFilesave.setObjectName("actionFilesave")
        self.actionAddChilditem = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/file-add-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddChilditem.setIcon(icon2)
        self.actionAddChilditem.setObjectName("actionAddChilditem")
        self.actionDeleteItem = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/file-reduce-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteItem.setIcon(icon3)
        self.actionDeleteItem.setObjectName("actionDeleteItem")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/file-settings-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon4)
        self.actionSettings.setObjectName("actionSettings")
        self.actionInsertItem = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/res/file-add-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertItem.setIcon(icon5)
        self.actionInsertItem.setObjectName("actionInsertItem")
        self.actionExpandtChildren = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/res/file-download-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExpandtChildren.setIcon(icon6)
        self.actionExpandtChildren.setObjectName("actionExpandtChildren")
        self.actionCollapseChildren = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/res/file-upload-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCollapseChildren.setIcon(icon7)
        self.actionCollapseChildren.setObjectName("actionCollapseChildren")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/res/file-3-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon8)
        self.actionNew.setObjectName("actionNew")
        self.actionImportCSV = QtWidgets.QAction(MainWindow)
        self.actionImportCSV.setObjectName("actionImportCSV")
        self.actionExportCSV = QtWidgets.QAction(MainWindow)
        self.actionExportCSV.setObjectName("actionExportCSV")
        self.actionRanked_CSV = QtWidgets.QAction(MainWindow)
        self.actionRanked_CSV.setObjectName("actionRanked_CSV")
        self.toolBar.addAction(self.actionFileopen)
        self.toolBar.addAction(self.actionFilesave)

        self.retranslateUi(MainWindow)
        self.actionFileopen.triggered.connect(MainWindow.fileopen)
        self.actionFilesave.triggered.connect(MainWindow.filesave)
        self.tableView.customContextMenuRequested['QPoint'].connect(MainWindow.execContextMenu)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF Joint"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "command browser"))
        self.actionFileopen.setText(_translate("MainWindow", "Open"))
        self.actionFileopen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionFilesave.setText(_translate("MainWindow", "Save"))
        self.actionFilesave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionAddChilditem.setText(_translate("MainWindow", "Add child item"))
        self.actionAddChilditem.setToolTip(_translate("MainWindow", "Add child item"))
        self.actionAddChilditem.setShortcut(_translate("MainWindow", "Ctrl+Shift+Num++"))
        self.actionDeleteItem.setText(_translate("MainWindow", "Delete Item"))
        self.actionDeleteItem.setToolTip(_translate("MainWindow", "Delete item"))
        self.actionSettings.setText(_translate("MainWindow", "Setting"))
        self.actionInsertItem.setText(_translate("MainWindow", "Insert item"))
        self.actionInsertItem.setShortcut(_translate("MainWindow", "Ctrl++"))
        self.actionExpandtChildren.setText(_translate("MainWindow", "Expand children"))
        self.actionCollapseChildren.setText(_translate("MainWindow", "Collapse children"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionImportCSV.setText(_translate("MainWindow", "CSV"))
        self.actionExportCSV.setText(_translate("MainWindow", "CSV"))
        self.actionRanked_CSV.setText(_translate("MainWindow", "Ranked CSV"))
import resource_rc
